### ISSUE TITLE
Gray buttons have a green active color

### ISSUE THREAD

**Issue by nicolaskempf57** [petalframework/petal_components#102]
Buttons without variant have an `active:bg-green-700` instead of `active:bg-gray-700`.

See https://github.com/petalframework/petal_components/blob/main/lib/petal_components/button.ex#L294

**Comment by mplatts** [comment]
Thanks @nicolaskempf57 ! Fixed in https://github.com/petalframework/petal_components/commit/9d4791e2e1e595507d5a5816cba42bdf384df370
