### ISSUE TITLE
REQUEST: Help text for form inputs

### ISSUE THREAD

**Issue by Rio517** [petalframework/petal_components#103]
Hello, 

It would be awesome to have built-in support to help text form input fields. Ideally, we could add an explicit "form_field_help" and an optional `help=` attr for the all-inclusive option. 

Of those above names that are agreeable, I could offer a PR, but it will take me quite a while. 

Thanks!

**Comment by mplatts** [comment]
Hey @Rio517 yeah I've wanted that too - agree with those names. 

I've still got to finish off and merge https://github.com/petalframework/petal_components/pull/97 so unsure when I can start this. Maybe in a couple of weeks -  if you can get it out before then let me know and I'll leave it with you.
