### ISSUE TITLE
Accordion - Create option for default drawer open

### ISSUE THREAD

**Issue by houllette** [petalframework/petal_components#110]
It would be awesome if we had the ability to add on create, being able to add a boolean option in the :item assigns to have whatever entry it belongs to be open on page load

**Comment by mplatts** [comment]
For now if you're using live_view_js you could try and put a snippet of javascript that finds the desired accordion panel and set `data-open='true'` on it. 

psuedo code:
- find a div inside `.my_accordion` with data-id=0
- on that div, set `data-open='true'`
