### ISSUE TITLE
Problems with custom 'class' in form_field components with 0.19.0 release

### ISSUE THREAD

**Issue by gtaranti** [petalframework/petal_components#111]
Something changed in 0.19.0 and broke my custom classes for form_field (text_inputs, selects, etc)
In 0.1.8.5 release I had coded for example 
`<.form_field type="text_input" form={f} class="w-max" />`
and 'w-max' was honoured (added to the input element)

After upgrading to 0.19.0
1. I inspected the element in Dev Tools, and saw that  this class is not added to the element.
2. Also, trying to override by doing `class="!w-max"`, it applies ONLY `'w-max'` and NONE of the text_input (or select) base_classes
3. Finally, by setting `class=""` (ie an empty string), it applies only the `"phx-no-feedback"` class and NONE of the base_classes

**Comment by mplatts** [comment]
Thanks I'll have a look ASAP

**Comment by gtaranti** [comment]
Thanks!!
