### ISSUE TITLE
Dropdown component cannot be stylistically customised with 'class'

### ISSUE THREAD

**Issue by gtaranti** [petalframework/petal_components#112]
Most of the components have the extra 'class' attribute (and some have wrapper_classes also) in order to accommodate easy customisation by the user.

Can you add this attribute to dropdown and dropdown_menu_item components?
When in dark mode, the default <td> background of the table component and dropdown_menu_item match.
So it is difficult to discern the borders of the dropdown.

Have a look at the video :
[Dropdown BG issue](https://i.imgur.com/UHrdauS.gifv)

**Comment by mplatts** [comment]
Thanks - I added class into both those components in the latest version (0.19.2). Also added `menu_items_wrapper_class` as an attribute.

```
<.dropdown
  class="mt-10"
  menu_items_wrapper_class="bg-blue-100"
 >
   <.dropdown_menu_item class="" />
</.dropdown> 
```

Let me know if this is enough
