### ISSUE TITLE
Local development

### ISSUE THREAD

**Issue by mustela** [petalframework/petal_components#115]
Hey there! 

Im trying to extend your library with a few custom components. So I have your library downloaded next to my project. 

```
petal_components
my_project
```

So in mix I have a local dependency to the library like `{:petal_components, path: "../petal_components"}`

The problem Im having is that `deps/petal_component` is no available when adding a local dependency, so the suggestion you made in the readme is no longer valid for me. 

```
// We need to include the Petal dependency so the classes get picked up by JIT.
"../deps/petal_components/**/*.*ex"
```

Im wondering what's your approach here? Do you just add a symb link to have `deps/petal....` or is there any other way of dealing with it for local development? 

Thanks a lot!!

**Comment by mplatts** [comment]
Hey I've set up an umbrella app here: https://github.com/petalframework/petal_development 

Just clone that and follow the instructions. Should allow you to add new components and play around with them by putting them on `home.html.heex` in petal boilerplate.

**Comment by mustela** [comment]
Ill take a look, thank you so much! 

But out of curiosity, using a symb link as I described above, is that too bad or not a good practice?

**Comment by mplatts** [comment]
I'm not sure to be honest. The way I got it to work was with the umbrella app... open to suggestions though if anyone else knows a better way
