### ISSUE TITLE
REQUEST: Date Only Select Input

### ISSUE THREAD

**Issue by Rio517** [petalframework/petal_components#121]
Hello, and thanks again for all the awesome work on [petal_components](https://github.com/petalframework/petal_components)!

If I may add another request: please add support for a **date-only** input field. 

With time-only and DateTime already supported, I hope extending support to date-only is a light lift.

Thanks so much!

:pray:

**Comment by mplatts** [comment]
Oh, we did add that. We added every input that Phoenix had a function for. Seems we forgot to document it though! I'll add that as a todo. You can use it right now though:

```
<.form_field type="date_input" form={f} field={:your_field} />
<.form_field type="date_select" form={f} field={:your_field} />
```

**Comment by mplatts** [comment]
https://petal.build/components/forms#date_input

**Comment by Rio517** [comment]
Don't know how I missed that, Thanks!
