### ISSUE TITLE
Form Labels don't forward `class` property 

### ISSUE THREAD

**Issue by Rio517** [petalframework/petal_components#122]
Hello, 

I was hoping to add class overrides to a form input label like so:

```
    <.form_label
      form={f}
      field={:name}
      label={dgettext("jobs", "A label with a class override")}
      class="!mb-0"
    />
```

Yet, I noticed that the rendered output doesn't seem to include the desired override.

```
<label class=" mb-2 font-medium text-sm block text-gray-900 dark:text-gray-200" for="user_name" phx-feedback-for="user[name]">
    
      A label with a class
    
  </label>
```

Can I request that the overriding behavior be extended to include labels?  

Please let me know if there is something I'm missing.  Thanks so much!

**Comment by mplatts** [comment]
The class attr currently gets passed on to the <input>. We could have another attr called `label_class` that passes the class to the label?

**Comment by mplatts** [comment]
This should work in the latest version:

```
  <.form_label
    form={f}
    field={:name}
    label={dgettext("jobs", "A label with a class override")}
    label_class="!mb-0"
  />
```
