### ISSUE TITLE
Warnings for 'undefined attributes' when using Phoenix 1.7.0.rc-1

### ISSUE THREAD

**Issue by gtaranti** [petalframework/petal_components#128]
In my project there are many warnings concerning "undefined attribute" in components like

- Dropdown.dropdown_menu_item
- Table.th
- Button.button

Warning examples :

`warning: undefined attribute "data" for component PetalComponents.Dropdown.dropdown_menu_item/1
  
warning: undefined attribute "phx_click" for component PetalComponents.Dropdown.dropdown_menu_item/1

warning: undefined attribute "phx_value_id" for component PetalComponents.Dropdown.dropdown_menu_item/1

warning: undefined attribute "phx_value_user_id" for component PetalComponents.Dropdown.dropdown_menu_item/1
  
warning: undefined attribute "colspan" for component PetalComponents.Table.th/1

warning: undefined attribute "phx_disable_with" for component PetalComponents.Button.button/1

warning: undefined attribute "data" for component PetalComponents.Button.button/1`

I'm using Phoenix 1.7.0.rc-1.
I don't know if has the same behaviour on Phoenix 1.6

**Comment by mplatts** [comment]
Thanks for this. The `phx_*` ones just need to be changed to dashes - eg. `phx-click`.

What do you use the `data` prop for?  

`colspan` seems to be an issue.

**Comment by mplatts** [comment]
Oh, luckily @paynegreen just fixed the `colspan` issue!

**Comment by mplatts** [comment]
Fixed in v0.19.9

**Comment by gtaranti** [comment]
Hey!
Thanks for this.
I've changed `phx_*` bindings to `phx-*` bindings.
Also I had the `data={[confirm: "Are you sure"]}` and changed it to `data-confirm="Are you sure?"`.

Along with the `colspan` fix, No more warnings !!
