### ISSUE TITLE
Beginner friendly contribution?

### ISSUE THREAD

**Issue by TwistingTwists** [petalframework/petal_components#13]
Are there some low hanging fruits that could get beginner involved? 

Or maybe a couple of decent sized issues that could be highlighted as per plan of the maintainers of library? 

Would love to contribute. Need a direction.

**Comment by mplatts** [comment]
![image](https://user-images.githubusercontent.com/184383/155269098-6e1b6b0e-3c8c-497e-809d-9ea1e0cd8813.png)

Not sure what level you're at, but some help text for the .form_field component would be handy like in the image above. It would probably look something like this:

![image](https://user-images.githubusercontent.com/184383/155269384-cbe63e70-55a1-4e05-9129-6c8e90a9004c.png)

**Comment by mplatts** [comment]
Also fyi, we made https://github.com/petalframework/petal_development to help with development - simply clone and then follow the readme instructions.
