### ISSUE TITLE
dependency Issue with installing Petal component

### ISSUE THREAD

**Issue by epinault** [petalframework/petal_components#136]
Hello

I am using Elixir 1.14.0, Phoenix 1.7.0 rc2 on OSX

I am tyring to play with Petal but I am having some installation issues

I am following the guide https://petal.build/components

and when just adding at first the latest version. I am getting some conflicts

❯ mix deps.get
Resolving Hex dependencies...
Resolution completed in 0.093s
Because your app depends on petal_components ~> 0.19 which depends on phoenix_live_view ~> 0.18.3, phoenix_live_view ~> 0.18.3 is required.
So, because your app depends on phoenix_live_view ~> 0.17.5, version solving failed.
** (Mix) Hex dependency resolution failed

I was able to resolve that conflict by upgrading 

phoenix_live_view 0.17.12 => 0.18.11
phoenix_live_dashboard 0.6.5 => 0.7.2

So that seems that like something is not setup right in terms of dependencies?

**Comment by mplatts** [comment]
Hey @epinault yeah we depend on the latest live view because of the new declarative attributes. I believe it's backwards compatible so upgrading shouldn't hurt your app
