### ISSUE TITLE
Issue when using Petal Component

### ISSUE THREAD

**Issue by epinault** [petalframework/petal_components#137]
Hello

I am using Elixir 1.14.0, Phoenix 1.7.0 rc2 on OSX. I am using   heroicons 0.5.2 and  petal_components 0.19.10

Also I am using phoenix_live_view 0.18.11

I am tyring to play with Petal but I am having some installation issues   

I am following the guide https://petal.build/components and trying to follow the section on "Replace container class in the live layout"

But I am geting this error when using your template.

❯ mix phx.server
Compiling 14 files (.ex)
warning: undefined function live_flash/2 (expected MartialNetworkWeb.LayoutView to define such a function or for it to be imported, but none are available)
  lib/martial_network_web/templates/layout/live.html.heex:8

== Compilation error in file lib/martial_network_web/views/layout_view.ex ==
** (CompileError) lib/martial_network_web/templates/layout/live.html.heex:4: undefined function live_flash/2 (expected MartialNetworkWeb.LayoutView to define such a function or for it to be imported, but none are available)

**Comment by epinault** [comment]
so I found the issue . we must use https://hexdocs.pm/phoenix/1.7.0-rc.2/Phoenix.Flash.html#get/2 in Phx 1.7 . it is marked as deprecated https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#live_flash/2

so your doc will need to be updated

**Comment by mplatts** [comment]
Thanks for this! I will update it

**Comment by mplatts** [comment]
Done
