### ISSUE TITLE
Does this slow down the rendering of components? 

### ISSUE THREAD

**Issue by TwistingTwists** [petalframework/petal_components#14]
https://github.com/petalframework/petal_components/blob/main/lib/petal_components/form.ex#L90

All the components are defined in one huge case statement. 

Usually , in other frameworks, such approaches use templates rather than invoking the components directly in case statement. Otherwise, they would load all the components and then hide some, based on Switch, pollluting the dom). 
 Hence  only one of the templates is invoked (hence faster loading)

See ng-template for example in Angular. 

My concern is - 

1. If i have a lot of components in switch case, does it  slow down  elixir  in determining which template to load? 
Because morphdom of phoenix removes the element and replaces it again in LiveView (i hope i understand this correctly 😅)

**Comment by mplatts** [comment]
Hi @TwistingTwists, to be honest I'm not sure. That would be a question for @chrismccord (creator of Phoenix).
My guess is a diff is produced from the final HTML, so it wouldn't matter how the HTML is generated (so a large switch statement wouldn't matter), but not overly sure.
