### ISSUE TITLE
Disabled buttons should not just look disabled

### ISSUE THREAD

**Issue by forest** [petalframework/petal_components#144]
Currently passing `disabled` to `<.button link_type="live_redirect" disabled>` makes the button look disabled but it can still be clicked and the action (redirect in this case) still happens.

**Comment by mplatts** [comment]
Weird - does is have the disabled attribute for you?:

<img width="385" alt="CleanShot 2023-02-22 at 13 51 37@2x" src="https://user-images.githubusercontent.com/184383/220509062-76747c17-ef59-4e35-9152-26a8285840be.png">

**Comment by forest** [comment]
I didn't try a basic button, but one with a link_type does not. Just the custom class.

**Comment by forest** [comment]
This `<.button label="Press me" phx-click="click_event" disabled />` renders:

`<button class="pc-button--primary pc-button--md pc-button--disabled pc-button" disabled phx-click="click_event">Press me</button>`.

And this `<.button link_type="live_redirect" label="Press me" to="/" phx-click="click_event" disabled />` renders:

`<a href="/" class="pc-button--primary pc-button--md pc-button--disabled pc-button" phx-click="click_event" data-phx-link="redirect" data-phx-link-state="push">Press me</a>`

I think the `phx-click` might need to be removed as well so nothing happens if the buttons are clicked. Might also be good to render a `<button>` instead of an `<a>` for disabled.

**Comment by mplatts** [comment]
Ah I see... good catch

**Comment by mplatts** [comment]
Fixed - https://github.com/petalframework/petal_components/releases/tag/v1.0.3
