### ISSUE TITLE
BUG: Namespaced components not working as documented

### ISSUE THREAD

**Issue by mindreframer** [petalframework/petal_components#147]
Thanks for the `petal_components` package, it looks great! I just have difficulties using in without clashing with provided Phoenix components. 
When I follow the docs, this is suggested: 

```
If you want to pick and choose which components to use, you could namespace Petal Components.

defmodule PC do
  use PetalComponents
end
```

This approach does not work for me. I've tried following: 

1. top-level module pc.ex with following content: 

```elixir 
defmodule PC do
  use PetalComponents
end
```

2. inlined module in MyAppWeb html_helper functions: 
```elixir
defp html_helpers do
    quote do
      # HTML escaping functionality
      import Phoenix.HTML
      # Core UI components and translation
      import MyAppWeb.CoreComponents
      import MyAppWeb.Gettext

      # Shortcut for generating JS commands
      alias Phoenix.LiveView.JS

      defmodule PC do
        use PetalComponents
      end
     # this prints `[]`
      IO.inspect(PC.__info__(:functions), label: :functions)

      # Routes generation with the ~p sigil
      unquote(verified_routes())
    end
  end
```

Html snippet that fails: 
```html
<div class="p-20 max-w-2xl items-center">
  <PC.button color="primary" label="Primary" variant="inverted" />
</div>
```

It seems, like this might be expected behaviour in Elixir...

```elixir
defmodule Hey do 
   import List
end

# this will not work
Hey.last([1])
```

Am I missing something?

**Comment by mplatts** [comment]
Thanks @mindreframer  - to be honest I just assumed it would work. @mitkins @braidonw do you guys have any ideas how to namespace it?

**Comment by mindreframer** [comment]
Thanks @mplatts! Yes, maybe take it from the documentation for now, because this is wrong and I've spend couple hours questioning my sanity, why it is not working on my machine. I just assumed the docs would be correct. 

For namespacing: it seem, that the macro needs to define the functions, importing them is not enough. Something like: 
```elixir
... 
def alert(assigns), do: PetalComponents.Alert.alert(assigns)
... 
```

It's repetitive, yet simple and without surprises. And it would work both when inlined in LiveComponent helpers or with a namespaced module. Codewise it would be same 20 lines, so not problems. But maybe you'll come up with a more elegant solution.

**Comment by mitkins** [comment]
Hi @mindreframer and @mplatts. I tried to think of something clever. But to be honest, I couldn't think of anything better than your solution @mindreframer. The only thing I could add, perhaps, is the use of `defdelegate`. It's slightly more concise:

```elixir
defmodule PC do
    defdelegate alert(assigns), to: PetalComponents.Alert
    defdelegate badge(assigns), to: PetalComponents.Badge
    ...
end
```

The [docs](https://hexdocs.pm/elixir/Kernel.html#defdelegate/2) define `defdelegate` as:

>  ...a function that delegates to another module
> 
> Functions defined with [defdelegate/2](https://hexdocs.pm/elixir/Kernel.html#defdelegate/2) are public and can be invoked from outside the module they're defined in, as if they were defined using [def/2](https://hexdocs.pm/elixir/Kernel.html#def/2). Therefore, [defdelegate/2](https://hexdocs.pm/elixir/Kernel.html#defdelegate/2) is about extending the current module's public API

Which sounds exactly like what you're trying to do!

**Comment by mindreframer** [comment]
@mitkins Thanks looks indeed a bit nicer! We could put this into the macro, instead of `import`-ing public functions, and this should avoid any surprises.

**Comment by CharlesIrvineKC** [comment]
I was going to create an issue asking for a way to namespace PetalComponents, but I see there is already this issue. 

I tried to use "alias PetalComponents, as: PC", but this didn't work.

FYI, I would rate this issue pretty high. Also, I think Phoenix should use alias in core_components.ex instead of importing.

**Comment by artimath** [comment]
@mitkins, that worked great for me so far.

```elixir
# Petal Components
defmodule PC do
  defdelegate accordion(assigns), to: PetalComponents.Accordion
  defdelegate alert(assigns), to: PetalComponents.Alert
  ...
end

alias PetalComponents.HeroiconsV1
```
      


So my `html_helpers` looks like:

```elixir
defp html_helpers do
    quote do
      # HTML escaping functionality
      import Phoenix.HTML
      # Core UI components and translation
      import FlowAppWeb.CoreComponents
      import FlowAppWeb.Gettext

      # Shortcut for generating JS commands
      alias Phoenix.LiveView.JS

      # Routes generation with the ~p sigil
      unquote(verified_routes())

      # Petal Components
      defmodule PC do
        defdelegate accordion(assigns), to: PetalComponents.Accordion
        defdelegate alert(assigns), to: PetalComponents.Alert
        defdelegate avatar(assigns), to: PetalComponents.Avatar
        defdelegate badge(assigns), to: PetalComponents.Badge
        defdelegate breadcrumbs(assigns), to: PetalComponents.Breadcrumbs
        defdelegate button(assigns), to: PetalComponents.Button
        defdelegate card(assigns), to: PetalComponents.Card
        defdelegate container(assigns), to: PetalComponents.Container
        defdelegate dropdown(assigns), to: PetalComponents.Dropdown
        defdelegate field(assigns), to: PetalComponents.Field
        defdelegate form(assigns), to: PetalComponents.Form
        defdelegate icon(assigns), to: PetalComponents.Icon
        defdelegate input(assigns), to: PetalComponents.Input
        defdelegate link(assigns), to: PetalComponents.Link
        defdelegate loading(assigns), to: PetalComponents.Loading
        defdelegate modal(assigns), to: PetalComponents.Modal
        defdelegate pagination(assigns), to: PetalComponents.Pagination
        defdelegate progress(assigns), to: PetalComponents.Progress
        defdelegate rating(assigns), to: PetalComponents.Rating
        defdelegate slide_over(assigns), to: PetalComponents.SlideOver
        defdelegate table(assigns), to: PetalComponents.Table
        defdelegate tabs(assigns), to: PetalComponents.Tabs
        defdelegate typography(assigns), to: PetalComponents.Typography
      end

      alias PetalComponents.HeroiconsV1
    end
  end
```

I can call Petal components as so:

```elixir
// _LIVEVIEW.HTML.HEEX_

PC.modal :if={@live_action in [:new_task, :edit_task]} id="task-modal" title="Add New Task">
  <.live_component
    module={DemoApp.PageLive.NewFormComponent}
    id={@task.id || :new}
    title={@page_title}
    action={@live_action}
    task={@task}
    patch={~p"/schedule"}
    project_options={@project_options}
    current_user={@current_user}
  />
</PC.modal>

// FORM_LIVE_COMPONENT.EX | DemoApp.PageLive.NewFormComponent

@impl true
def render(assigns) do
  ~H"""
  <div>
    <.form for={@form} phx-submit="on_submit" phx-target={@myself}>
      <PC.field field={@form[:title]} />
      <PC.field field={@form[:notes]} />
    </.form>
  </div>
end


```

And voila:

![2023-06-24_19-05-02](https://github.com/petalframework/petal_components/assets/19831746/31dc2186-e41d-4dff-8be4-52665dfdd9eb)

**Comment by mitkins** [comment]
I like it. Looks succinct enough and self-descriptive

**Comment by artimath** [comment]
> I like it. Looks succinct enough and self-descriptive

@mitkins, I'm a professional writer in my other life, so if you want assistance in converting this namespacing exploration into workable documentation to add to the main site...

just let me know, happy to contribute however I can!

**Comment by mplatts** [comment]
@artimath thanks for offering this! Our petal.build site is private but under the hood it's just markdown. So if you could either modify your above comment or add one underneath with the appropriate docs - I'll cut and paste it straight into the install docs for petal components.

**Comment by nhobes** [comment]
Hey guys, not sure where this conversation concluded, but closing this one for now to keep the current issues clear. Feel free to add a new issue or get in touch if there's anything further.
