### ISSUE TITLE
Q: Support for optimized form field access?

### ISSUE THREAD

**Issue by DaTrader** [petalframework/petal_components#170]
I am still using PetalComponents v0.18.5 for some compatibility reasons, but judging by your code base, the optimization is not supported in the newer versions either, right?

Thanks

**Comment by mplatts** [comment]
No we haven't upgraded to use the new `to_form` yet sorry! What are the benefits of that again? Performance optimisation?

**Comment by DaTrader** [comment]
Yes, of course. Performance optimization i.e. a reduction of the data sent over the wire. I tried it the other day by mixing your attributes building source code (from v0.18.5) and altering a LV-generated `CoreComponents.input/1`. It worked splendidly. Only the related chunks of the form data were transferred to the client (when you have large or multi-part forms it matters a lot).

Although, I am still unhappy about certain aspects of the LV form optimization. Classes get sent over regularly even if unchanged and the sometimes massive `Phoenix.LiveView.JS` data as well, but that particular rant regards LV as such not your components.

**Comment by mplatts** [comment]
Done in v1.1.0. https://github.com/petalframework/petal_components/commit/791276f7b97e66ab3e69966df07e4cf145a55b71

Docs coming soon
