### ISSUE TITLE
`group-hover/pc-icon-button:flex` class does not exist

### ISSUE THREAD

**Issue by henryoswald** [petalframework/petal_components#177]
I bumped up to 1.0.7 and am being shown the following error which seems valid to me:

```
CssSyntaxError: tailwindcss: deps/petal_components/assets/default.css:190:3: The `group-hover/pc-icon-button:flex` class does not exist. If `group-hover/pc-icon-button:flex` is a custom class, make sure it is defined within a `@layer` directive.

  188 |
  189 | .pc-icon-button__tooltip {
> 190 |   @apply absolute flex-col items-center invisible mb-6 -translate-y-full -top-1 group-hover/pc-icon-button:flex group-hover/pc-icon-button:visible group-hover/pc-icon-button:opacity-100 opacity-0 transition-opacity duration-300;
      |   ^
  191 | }
  192 |
```

**Comment by mplatts** [comment]
Hmm yeah it should work as long as `pc-icon-button` is defined in the file. We can probably remove the reference to pc-icon-button though @fredwu ? The group class should be enough to work

**Comment by fredwu** [comment]
I'm not sure the group name is the cause:

> Groups can be named however you like and don’t need to be configured in any way — just name your groups directly in your markup and Tailwind will automatically generate the necessary CSS.

https://tailwindcss.com/docs/hover-focus-and-other-states#differentiating-nested-groups

Removing the group name will cause the button to not be embeddable in a parent group. as the parent group will affect the visibility of the button.

**Comment by fredwu** [comment]
@henryoswald could you please check to see what version of Tailwind is configured?

In `config/config.exs`:

```elixir
config :tailwind,
  version: "3.3.1",
  #...
```

And do a `mix tailwind.install` to make sure the specified version is used.

**Comment by henryoswald** [comment]
Thanks, I was on 3.1.8 still from my petal_pro clone. I didn't realise there was a separate place to specify the version.

All sorted now.
