### ISSUE TITLE
checkbox_group form field has an extra empty string 

### ISSUE THREAD

**Issue by tmaszk** [petalframework/petal_components#178]
Only happens with version 1.0.7
![group_checkbox](https://user-images.githubusercontent.com/4540522/235789697-53473f30-da72-4c08-a96c-95dc6fa1c6de.jpg)

**Comment by fredwu** [comment]
This one is my fault.

Due to the inconsistent output (empty selection resulting in a string, rather than a list), I changed it and I filter the empty string on the server end.

Perhaps we can revert this change if it's causing confusion. cc @mplatts

**Comment by fredwu** [comment]
One thing I'm curious about though, is how does everyone handle the `""`?

By default the empty string is rejected by Phoenix, e.g.

```
** (ArgumentError) value for checkbox "my[pets][]" must be one of ["d371b96e-af9e-4573-acd3-e864f3b0b961", "9bc7ace3-9270-4c8c-9c18-6f05476265f8", "23d46b3c-6dd6-4aa9-b53e-cc84de4b7178", "cbd93b84-9ae6-4580-86a6-8c0b4001491a"], got: ""
```

**Comment by mplatts** [comment]
Would depend how you handle the params. For me I'd handle in the schema file with a function that takes a changeset. For these list type scenarios I'd create a virtual field on the schema - eg post.tags_as_strings, and then in a function that takes a changeset it could turn those into structs representing a Tag or whatever processing is needed. If the value is an empty string it could pattern match or check for that and change it to an empty array or something.

**Comment by mplatts** [comment]
I think let's revert this change though as it's affecting cases where items are checked correctly

**Comment by mplatts** [comment]
Reverted in 1.0.8
