### ISSUE TITLE
Random id in dropdown may conflict

### ISSUE THREAD

**Issue by joshprice** [petalframework/petal_components#18]
Using random ids in dropdown isn't safe. Although unlikely, if there is a conflict, then this will be problematic.

https://github.com/petalframework/petal_components/blob/main/lib/petal_components/dropdown.ex#L34

Maybe use a more reliable ID generator like UUID?

**Comment by mplatts** [comment]
Thanks @joshprice  - should this work? https://github.com/petalframework/petal_components/commit/dbc2a52f45e5cec0399013f8fab790f182e9063b

**Comment by cohawk** [comment]
FYI - don’t really need an additional library for UUIDv4 since Ecto has it built in - https://hexdocs.pm/ecto/Ecto.UUID.html

Ecto.UUID.generate

**Comment by mplatts** [comment]
https://github.com/petalframework/petal_components/commit/4b19d706d61f8f43ae31308cda3199e79d17da7e

**Comment by joshprice** [comment]
Thanks!

**Comment by joshprice** [comment]
@mplatts just noticed that you've only included `phoenix_ecto` for test env only, will need this in all envs?
