### ISSUE TITLE
Empty help text adding undesirable margin

### ISSUE THREAD

**Issue by Rio517** [petalframework/petal_components#181]
I'm using `  <.form_field type="date_input" ... />` with no help text specified. However, the DOM renders an empty DOM element `<p class="pc-form-help-text "> </p>` with some space in it.  Given that pc-form-help-text has a top margin of 0.5rem, this adds an undesirable margin to the layout.

I'd recommend hiding the help text DOM element if it isn't used.

**Comment by mplatts** [comment]
Thanks @Rio517 .  Fixed in 1.1.3.
