### ISSUE TITLE
Request: individually disable a checkbox when using checkbox-group

### ISSUE THREAD

**Issue by msramos** [petalframework/petal_components#189]
When using `checkbox-group`, it's not possible to individually give a `disabled` attribute to an individual checkbox - it's all or nothing:

```
<.field
    field={@form[:field]}
    label="My Checkboxes"
    type="checkbox-group"
    class="grid grid-cols-3 gap-4"
    options={my_options()}
    group_layout="col"
    help_text={@help_text}
    disabled={@disabled} # disables/enabled all checkboxes
/>
```

I have a use case where, inside a group of checkboxes, I need to disable _some_ of them.

A few ideas to do that:
- Passing a list of disabled values
- Passing a function to be evaluated
- Accepting an optional third arg on the `options` tuple, where could say if the checkbox for that option is enabled/disabled.

**Comment by mplatts** [comment]
Fixed in latest version: https://github.com/petalframework/petal_components/compare/v1.2.1...v1.2.2

```
       <.field
          type="checkbox-group"
          field={@form[:roles]}
          options={[{"Option 1", "1"}, {"Option 2", "2"}, {"Option 3", "3"}]}
          disabled_options={["1", "3"]}
        />
```

Styling might need improvement for disabled options though. Let me know how you go
