### ISSUE TITLE
v2 form with datetime_select input and builder function does not work

### ISSUE THREAD

**Issue by gtaranti** [petalframework/petal_components#193]
In a project, I'm using v1 forms and Phoenix 1.7 for a while now .

In form v1 the following code works well :
`  <.form_field
               form={f}
                type="datetime_select"
                field={:eta_from}
                label="Bunker from"
                builder={datetime_builder()}
                month={[options: month_options()]}
                year={[options: year_options()]}
                default={DateTime.utc_now()}
              />`

When I convert it to form v2 :
`              <.field
                type="datetime_select"
                field={@form[:eta_from]}
                label="Bunker from"
                builder={datetime_builder()}
                month={[options: month_options()]}
                year={[options: year_options()]}
                default={DateTime.utc_now()}
              />`

it raises with error :
`protocol Phoenix.HTML.Safe not implemented for #Function<2.129335184/1 in BasWeb.LiveHelpers.datetime_builder/0> of type Function....`

Is there anything I can do to fix it?

**Comment by mplatts** [comment]
datetime_select was originally using [this function](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html#datetime_select/3) under the hood, which doesn't work with the new form structure. You could instead try using the browser default datetime select with `<.field type="datetime-local" ...` ([docs](https://petal.build/components/forms#datetime_local))

**Comment by mplatts** [comment]
If you like the datetime_select way better then for that form it may be better to stick with forms v1. Otherwise we would have to create this datetime_select from scratch to work with this new form structure in phx 1.7 (open to PRs though)

**Comment by gtaranti** [comment]
Thanks,
I may try to convert to the `datetime-local`
