### ISSUE TITLE
Petal Component Form fields require field name as atom - running out of atoms?

### ISSUE THREAD

**Issue by tjchambers** [petalframework/petal_components#196]
I have a number of dynamically generated forms similar to those described by this issue with another package [running out of atoms](https://elixirforum.com/t/dynamically-generated-forms-and-running-out-of-input-atoms/38582) . Afaict - may be mistaken - I cannot specify a form field as a string (and therefore avoid chewing through atoms). 

Is there a workaround for this?

**Comment by mplatts** [comment]
Hmm not sure there is a quick fix. Maybe try with our new [`<.field>` component](https://petal.build/components/forms#field).
