### ISSUE TITLE
Pagination broken with less than 5 pages

### ISSUE THREAD

**Issue by philipgiuliani** [petalframework/petal_components#21]
The pagination element doesn't seem to work correctly when using less than 5 total pages.
I am using it like:

```
<.pagination link_type="a" path={Routes.dashboard_news_path(@conn, :index)} current_page={1} total_pages={2} />
```

![Screenshot 2022-03-04 at 10 14 09](https://user-images.githubusercontent.com/5446019/156734507-79c7128b-c6c5-42ba-bb81-48e3f6ac758b.png)

**Comment by nhobes** [comment]
Thanks @philipgiuliani, looking into it.

**Comment by nhobes** [comment]
Thanks, just pushed a fix in the latest version.

**Comment by philipgiuliani** [comment]
Thanks! Worked perfectly now 👍
