### ISSUE TITLE
Combobox - Not updating on options change

### ISSUE THREAD

**Issue by safari12** [petalframework/petal_components#212]
The combo box component does not update when the liveview update its options. The options I have for the combo box component are dynamic based on another select / dropdown's selection, but its not reflecting the new options / list

**Comment by mplatts** [comment]
Just pushed an update - can you try 0.4.7?

**Comment by safari12** [comment]
Thank you, its working now :)

**Comment by safari12** [comment]
Thank you, its working now :)

**Comment by nallwhy** [comment]
@mplatts 
This bug still occurs when the initial value of options is `[]`.

**Comment by nallwhy** [comment]
I've fixed it and not updated other attrs also.
