### ISSUE TITLE
Typo on petal.build/components/combo-box

### ISSUE THREAD

**Issue by artimath** [petalframework/petal_components#215]
Figured this was decent place to add this here? If the page was open source, I would have done a PR as a token of appreciation ;)

[Direct Link to Typo Location](https://petal.build/components/combo-box#:~:text=in%20your%20live-,veiw,-return%20a%20list
)
![2023-06-24_18-39-28](https://github.com/petalframework/petal_components/assets/19831746/47f69c08-fadc-4d95-be52-b91c3c44f674)

**Comment by mplatts** [comment]
Thanks! fixed
