### ISSUE TITLE
Replace currency_formatter with money

### ISSUE THREAD

**Issue by dvic** [petalframework/petal_components#218]
I noticed that `DataTable` is using `currency_formatter`, which in return is depending on `Poison` ([to decode JSON](https://github.com/search?q=repo%3Asmeevil%2Fcurrency_formatter%20Poison&type=code) 🤷🏻‍♂️ ). I'd like to avoid depending on Poison and would like to propose to switch over to the dependency-free and better maintained [`money`](https://hexdocs.pm/money/readme.html) library (which also supports formatting).

What do you think?

**Comment by mplatts** [comment]
thanks, added to our todo list. Also added you to the petal_framework repo if you'd like to submit a PR and get it out sooner. My head is deep in Stripe stuff atm

**Comment by dvic** [comment]
> thanks, added to our todo list. Also added you to the petal_framework repo if you'd like to submit a PR and get it out sooner. My head is deep in Stripe stuff atm

Thanks! Here it is: https://github.com/petalframework/petal_framework/pull/38
