### ISSUE TITLE
Add optional asterisk to required fields

### ISSUE THREAD

**Issue by kraleppa** [petalframework/petal_components#221]
Hi there 👋 Thanks for petal it makes my life easier every day!

Minor issue from my side - is there a chance to add a red asterisk next to the label of a required field? It could be an optional argument of the field because I can imagine that not everyone wants such a feature.

I was able to handle it by writing some crazy CSS, but it'd really cool to have it inside the library

![Screenshot 2023-07-07 at 10 33 32](https://github.com/petalframework/petal_components/assets/56135216/7ad880b7-09d3-4424-b6a8-76c8f1a8df83)

**Comment by mplatts** [comment]
Sounds good. I'm thinking `<.field required_asterisk required field={@form[:text]} />`  in case someone may want a required but without the asterisk.

**Comment by mplatts** [comment]
Thoughts?

**Comment by mplatts** [comment]
Fixed in 1.2.14: 
https://github.com/petalframework/petal_components/pull/226
https://github.com/petalframework/petal_components/releases/tag/v1.2.14
