### ISSUE TITLE
Modal hide event is broken

### ISSUE THREAD

**Issue by sezaru** [petalframework/petal_components#224]
The dialog will only work correctly if the user don't adds an id to the component.

That's because one of the JS events being pushed in the `hide_modal` function has `"#modal"` hardcoded where it should be `"##{id}"`

https://github.com/petalframework/petal_components/blob/453bffc2c832408fbe830e34caffe52ffc93589c/lib/petal_components/modal.ex#L93

**Comment by nhobes** [comment]
@sezaru thanks for the fix!

https://github.com/petalframework/petal_components/pull/225
