### ISSUE TITLE
input fields components ignores class attributes

### ISSUE THREAD

**Issue by sezaru** [petalframework/petal_components#238]
Some of the input components, for some reason, ignore some of the passed attributes, more specifically, the select and textarea inputs ignore the passed `class` attribute:

https://github.com/petalframework/petal_components/blob/23c9c4312033e4b3d74a769faa309c646b3f593c/lib/petal_components/input.ex#L46
https://github.com/petalframework/petal_components/blob/23c9c4312033e4b3d74a769faa309c646b3f593c/lib/petal_components/input.ex#L55

Why is that? Why can't these inputs just merge the user classes with the default one instead of replacing it?

Just to give a scenario for why I need this. I want a select input where I want to remove border radius for the top and bottom left side, so I'm trying to pass `class="rounted-r-none"` to the input component, but, as shown in the above code lines, this will just be ignored.

**Comment by mplatts** [comment]
Yeah you're right, it should merge the class attributes.

**Comment by nhobes** [comment]
This has been fixed in 1.4.3, thanks for reporting!
