### ISSUE TITLE
Add `disabled` attribute to `Tabs` `.tab` component

### ISSUE THREAD

**Issue by jpramassini** [petalframework/petal_components#254]
I have a situation where I'd like to be able to selectively disable access to specific tabs. This requires disabling clicks (or at least linking to the underlying route the tab is connected to). Conveniently, the underlying `Link` component supports this attribute already and passing the `disabled` attribute through the `.tab` components already works perfectly, but raises warnings about the `disabled` attribute being undefined. Adding this attribute to the tabs themselves would allow for some nice free added functionality without wrestling with attribute warnings. 

Happy to put up a PR for this, just wanted to make sure that was something that made sense to you before doing it.

**Comment by mplatts** [comment]
Hey yep a PR would be accepted for this!
