### ISSUE TITLE
Wrong cursor on disabled link

### ISSUE THREAD

**Issue by TillRauch** [petalframework/petal_components#260]
When hovering over a disabled button the cursor correctly shows as `not-allowed`. However, when hovering over a disabled button that has `link_type="a"` set, the cursor instead shows as `pointer`.

This can also be replicated in a plain [petal-boilerplate](https://github.com/petalframework/petal_boilerplate) environment:
![grafik](https://github.com/petalframework/petal_components/assets/5960259/d3b24834-142e-4848-8aec-6de79d4a30b8)

**Comment by mplatts** [comment]
Should be fixed in 1.6.0
