### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by couhajjou-apps** [petalframework/petal_components#277]
<img width="940" alt="Screenshot 2023-10-23 at 10 32 50 AM" src="https://github.com/petalframework/petal_components/assets/128639305/843e71cd-5592-41a2-bf23-972c5356c399">
<img width="590" alt="Screenshot 2023-10-23 at 10 33 35 AM" src="https://github.com/petalframework/petal_components/assets/128639305/a8722f2d-81e3-4b9b-9b53-d175775da9ad">
<img width="721" alt="Screenshot 2023-10-23 at 10 33 45 AM" src="https://github.com/petalframework/petal_components/assets/128639305/80f91561-e094-43d5-8a88-06a44eb8de29">

**Comment by mplatts** [comment]
Thanks working on it now. Looks like Fly stopped the DB server for some reason 😢

**Comment by mplatts** [comment]
Fixed
