### ISSUE TITLE
`no function clause matching in PetalComponents.Button.get_color_classes/1`

### ISSUE THREAD

**Issue by leeduckgo** [petalframework/petal_components#281]
Happened when I create a new proj by the newest version.

**Comment by leeduckgo** [comment]
works after I delete all the `dark` btns.

**Comment by arnaudbzn** [comment]
Same issue for me. Temporary fixed with @leeduckgo solution

**Comment by mitkins** [comment]
Looks like `get_color_classes` isn't a thing anymore
