### ISSUE TITLE
Breaking change tracking?

### ISSUE THREAD

**Issue by paulstatezny** [petalframework/petal_components#3]
A colleague pointed this out, and I wanted to give you a heads up as a courtesy.

For reference: https://github.com/petalframework/petal_components/blob/main/lib/petal/button.ex

When you do `assigns[:foo]` it breaks change tracking for the component. In summary, LiveView will send HTML over the wire that hasn't changed every time an event fires.

This is outlined here: https://hexdocs.pm/phoenix_live_view/assigns-eex.html#pitfalls

**Comment by paulstatezny** [comment]
In a particularly egregious example, I've had a large page that sent something like 30kb+ of unchanged HTML to the client *every keystroke* in a form.

A really bad situation to put clients on a mobile connection with limited data/bandwidth.

**Comment by mplatts** [comment]
Thanks @paulstatezny - I didn't realise that. I'll try using `assign_new` to set defaults at the top of the functions

**Comment by paulstatezny** [comment]
For sure 👍

If you want to check if a slot is assigned, instead of `if assigns[:slot_name]` you can do `if slot_assigned?(:slot_name)` to check without messing up change tracking.

For non-slot assigns, unfortunately there's no good option beyond setting `default: nil`.

Things like `button_classes(assigns)` in markup will break change tracking. I think referencing `assigns` at all will do it. The way that doesn't break it per the docs I linked is `button_classes(@foo, @bar, @baz, ...)`. More wordy, but properly optimized.

**Comment by mplatts** [comment]
Good to know 👏 . 

Yeah seems `slot_assigned?` is Surface only. I'll just default `@inner_block` to `nil` and keep the conditional.
