### ISSUE TITLE
Better intersection of class attributes

### ISSUE THREAD

**Issue by gregoribic** [petalframework/petal_components#31]
I would be nice that components filter out class attributes that are custom assigned.
Overriding classes does not always work.
Function for assigning class for example to <.td> element, could check if user assigned px-2 and therefore not assigning px-6.

**Comment by mplatts** [comment]
You should be able to go `!px-2`

**Comment by mplatts** [comment]
But agree in future we could have some kind of function that replaces existing classes so we don't have to set !important

**Comment by gregoribic** [comment]
Thew issue is that using ! does not work in all cases. Sometimes yes sometimes no.

**Comment by mplatts** [comment]
Oh right in that case yeah we should prioritise that

**Comment by mplatts** [comment]
Replaced by this issue: https://github.com/petalframework/petal_components/issues/35
