### ISSUE TITLE
Text in primary progress bar has low contrast in light mode

### ISSUE THREAD

**Issue by damir** [petalframework/petal_components#316]
![Screenshot 2024-03-30 at 2 13 34 PM](https://github.com/petalframework/petal_components/assets/7764/b7f73ddb-745d-4798-b597-e72a97fcb58d)

**Comment by nhobes** [comment]
Thanks Damir, I think the best way to solve this would be to update the styles in your app.ss file if you have a lighter primary color.

Say your primary color is blue-200, then I would recommend changing/adding to the .pc-progress__label styles:

"text-primary-900 dark:text-white"

Then it should look something like the below. Hope that makes sense.

![CleanShot 2024-05-27 at 12 53 42@2x](https://github.com/petalframework/petal_components/assets/20067021/61987539-0cc2-41e2-b002-d17fc372c620)
