### ISSUE TITLE
DOCS: conflict when using input field function

### ISSUE THREAD

**Issue by belgoros** [petalframework/petal_components#353]
Using phoenix `1.7.14` I see an error when declaring an `input` in a form as follows:
```elixir
<.form for={@form} phx-submit="save">
  <div class="w-4/5 mb-6">
    <.input field={@form[:name]} />
    <.button>Save</.button>
   </div>
</.form>
```

The error:
```
function input/1 imported from both PetalComponents.Input and MyAppWeb.CoreComponents, call is ambiguous
```

The latest [Petal documentation](https://petal.build/components) doesn't mention the need to comment it out or remove:

> To fix, go to the generated core_components.ex file and rename or remove the following functions: modal, button and table.

Petal version: `{:petal_components, "~> 2.0.3"},`,
Used phoenix version: `{:phoenix, "~> 1.7.14"},`
Elixir: `elixir 1.17.1-otp-27`

**Comment by mitkins** [comment]
Good point. There is some documentation under the title "Phoenix 1.7 and above", but it doesn't mention the `.input` component. I'll update the documentation

**Comment by mitkins** [comment]
The documentation has been updated 🙂
