### ISSUE TITLE
undefined function button_group/1

### ISSUE THREAD

**Issue by alexvinidiktov** [petalframework/petal_components#359]
Run mix setup. Get error message

error: undefined function button_group/1 (expected PetalBoilerplateWeb.PageLive to define such a function or for it to be imported, but none are available)
    │
 66 │       <.button_group aria_label="Size options" size={@group_size}>
    │       ^^^^^^^^^^^^
    │
    └─ lib/petal_boilerplate_web/live/page_live.ex:66:7: PetalBoilerplateWeb.PageLive.render/1

== Compilation error in file lib/petal_boilerplate_web/live/page_live.ex ==
** (CompileError) lib/petal_boilerplate_web/live/page_live.ex: cannot compile module PetalBoilerplateWeb.PageLive (errors have been logged)

**Comment by nhobes** [comment]
@alexvinidiktov apologies - we haven't yet updated the petal_components version in petal_bolerplate to the latest (2.2.0). If you do this, you will be able to get it up and running.

Modify the version here:
![CleanShot 2024-10-10 at 13 03 36@2x](https://github.com/user-attachments/assets/d4c07bfd-fde2-4522-94d6-94690222cf21)

Run `mix.setup` again -> `mix phx.server`
