### ISSUE TITLE
Button group usage throws compiler errors

### ISSUE THREAD

**Issue by tshakah** [petalframework/petal_components#367]
I initially reported this [here](https://github.com/phoenixframework/phoenix_live_view/issues/3487) as I wasn't sure it was an expected use case that was missed, please see that issue for more details.

As the `button` slot in button groups has a `do` block ([here](https://github.com/petalframework/petal_components/blob/main/lib/petal_components/button_group.ex#L64)) the `validate_attrs` opt is ignored, so using attrs like `phx-click` throws errors - you can see this in LiveView 0.20.17+, despite the docs for button group saying that fixed it.

**Comment by mitkins** [comment]
Hi @tshakah I've recently reviewed `validate_attrs` and came to the same conclusion. I'm thinking that for now we'll probably remove the `do` block
