### ISSUE TITLE
Use git tags for versions

### ISSUE THREAD

**Issue by moogle19** [petalframework/petal_components#37]
It would be nice to add a git tag for each (new) version. 
This would make viewing changes between two versions easier (e.g. `git diff v0.15.0 v0.16.0`).

**Comment by mplatts** [comment]
Our script actually does tag it but I just realised we hadn't been git pushing the tags... We will try to push up all tags from our local machines today - hopefully we didn't lose many.

**Comment by mplatts** [comment]
Added to the release instructions to push up tags

**Comment by mplatts** [comment]
@moogle19 fyi all tags should be there now.
