### ISSUE TITLE
Compile warnings originating in `lib/petal_components_web/a11y_live.ex`

### ISSUE THREAD

**Issue by grzuy** [petalframework/petal_components#371]
Hi there :wave: 

Seeing quite a few compile warnings coming from `lib/petal_components_web/a11y_live.ex` for a Phoenix application depending on `petal_components` 2.5.2.

![image](https://github.com/user-attachments/assets/50cf008b-267b-48cf-9192-bca4bc065686)

Anyone else?

**Comment by grzuy** [comment]
Is `lib/petal_components_web/a11y_live.ex` file really intended to be included in `petal_components` published releases? Or only development and testing?

If only dev and test, should it be moved to `test/support/`?
So it's not included in releases and in end user applications?

Thanks in advance.

**Comment by grzuy** [comment]
To provide some more context.

Seen that it was added in this https://github.com/petalframework/petal_components/pull/326/files#diff-443233b9c679556d43885b3f3babee59b9c5c33da48887d591513e423d558f3bR17 and apparently called only from the `test/test_helper.exs`. Reason why I was wondering it was a test only utility or not.

**Comment by mitkins** [comment]
Hi @grzuy with regards to the warning messages, this is being addressed in https://github.com/petalframework/petal_components/pull/368.

With regards to `a11y_live.ex`. Yes, it is for development and testing. It looks like the main reason why it's in the `lib/petal_components_web` is so you can do the following:

```
$ iex -S mix
iex> Run.playground()
```

Is it mainly the warning messages that you're concerned with?

**Comment by grzuy** [comment]
Yes, that fixes it.
Thank you.
