### ISSUE TITLE
Compatibility with Phoenix Live View 1.0

### ISSUE THREAD

**Issue by grzuy** [petalframework/petal_components#378]
Hi :wave: 

Apps using `petal_components` can't currently upgrade to Phoenix Live View 1.0 given `petal_components` define it's compatibility in `mix.exs` as `{:phoenix_live_view, "~> 0.20"}`.

Thanks.

**Comment by nhobes** [comment]
Just released in [2.7.4](https://github.com/petalframework/petal_components/releases/tag/v2.7.4) :)
