### ISSUE TITLE
Add petal to existing live view project error

### ISSUE THREAD

**Issue by howdoicomputer** [petalframework/petal_components#41]
I've tried adding petal to an existing project but I'm getting a compilation error:

```
== Compilation error in file lib/questioneer_web/live/question_live/index.ex ==
** (CompileError) lib/questioneer_web/live/question_live/index.html.heex:4: function modal/1 imported from both PetalComponents.Modal and QuestioneerWeb.LiveHelpers, call is ambiguous
    (elixir 1.13.4) expanding macro: Kernel.if/2
    lib/questioneer_web/live/question_live/index.html.heex:3: QuestioneerWeb.QuestionLive.Index.render/1
    (phoenix_live_view 0.17.9) /home/howdoicomputer/workspace/questioneer/lib/questioneer_web/live/question_live/index.ex:1: Phoenix.LiveView.Renderer.__before_compile__/1
```

It looks like the Phoenix 1.6 project generation creates a helpers file that includes a modal and Petal conflicts with it. I was able to resolve it by removing the import statement for the generated `<app>Web.LiveHelpers` file.

**Comment by mplatts** [comment]
I think if it's only if you run a generator (did you run `mix phx.gen.live`)? It creates a `live_helpers.ex` file which includes the modal function. So yeah, can either do what you did or you can delete that function in live_helpers and it'll work.

**Comment by howdoicomputer** [comment]
Sorry, this was more of a notification. I already know how to solve it. It's just that integrating petal into an already built LiveView enabled project will raise this error and this eventuality may need to be covered in documentation.

**Comment by mplatts** [comment]
Fixed https://test.petal.build/components#install_petal_components
