### ISSUE TITLE
form_field_error breaks on unsafe_unique validation error

### ISSUE THREAD

**Issue by msonawane** [petalframework/petal_components#43]
on following changeset

```
#Ecto.Changeset<
  action: :insert,
  changes: %{
    email: "xy@x.com",
    first_name: "b",
    inserted_by_id: 1,
    last_name: "b",
    password: "**redacted**",
    updated_by_id: 1
  },
  errors: [email: {"no", [validation: :unsafe_unique, fields: [:email]]}],
  data: #Quailx.Accounts.User<>,
  valid?: false
>
```

warning: the fallback message translator for the form_field_error function cannot handle the given value.

Hint: you can set up the `error_translator_function` to route all errors to your application helpers:

  config :petal_components, :error_translator_function, {MyAppWeb.ErrorHelpers, :translate_error}

Given value: [:email]

Exception: cannot convert the given list to a string.

To be converted to a string, a list must either be empty or only
contain the following elements:

  * strings
  * integers representing Unicode code points
  * a list containing one of these three elements

Please check the given list or call inspect/1 to get the list representation, got:

[:email]

**Comment by mplatts** [comment]
In your `config.exs` you can set up a translator:

```elixir
config :petal_components, :error_translator_function, {YourAppWeb.ErrorHelpers, :translate_error}
```

(Replace the text `YourApp` with your app name)

**Comment by msonawane** [comment]
aha thanks! closing it
