### ISSUE TITLE
Which tool do you use to generate the documentation?

### ISSUE THREAD

**Issue by carlotm** [petalframework/petal_components#48]
First of all, kudos for the project! Wish you all the best!

Mine is a simple question:
which tool (if any) do you use to generate the component documentation?
I am especially interested in the properties section.

Thank you

**Comment by mplatts** [comment]
Thanks @carlotm! I'm sorry to report that it's all manually coded. Maybe once 0.18 is released with their new `attr` macro it'll be easier to do an auto-generation script.
