### ISSUE TITLE
Highlight that you need to include petal in tailwind css config

### ISSUE THREAD

**Issue by Hanspagh** [petalframework/petal_components#52]
Hi.
First time user here. 
It was not clear to me it was need to add `"../deps/petal_components/**/*.*ex"` to my tailwind css config, ended up spending quite some time debugging why the components didnt work

**Comment by mplatts** [comment]
Oh sorry you're right - that part seemed to have slipped out of the install docs. Will fix it now

**Comment by mplatts** [comment]
Fixed http://petal.build/components#install_tailwind
