### ISSUE TITLE
translate_error for forms not working when use Ecto.Changeset.unsafe_validate_unique

### ISSUE THREAD

**Issue by mohammedzeglam-pg** [petalframework/petal_components#54]
i was using petal component but i wrote different set component for my project and i was using a lot of petal component source code because in my opinion it is awesome lib but when i used unsafe_validate_unique and the default the phoenix generate better and works fine with gettext

**Comment by mplatts** [comment]
You might have to put this in your config:

```
config :petal_components, :error_translator_function, {<YourApp>Web.ErrorHelpers, :translate_error}
```
