### ISSUE TITLE
Modal content padding attribute

### ISSUE THREAD

**Issue by rupurt** [petalframework/petal_components#69]
## Problem

When I use the modal
Then I would like to control the content padding
So that I can create more interesting designs

https://github.com/petalframework/petal_components/blob/12a47d927d87e271345e2e1ce0c43a4fca88fe66/lib/petal_components/modal.ex#L59

## Suggested Solution

Add new attribute similar to `size`

```
prop content_padding, :string
```

**Comment by nhobes** [comment]
@rupurt thanks for your patience. We're looking into options of making petal components more extendable (perhaps something like daisyUI does) and should help solve issues like these. Hopefully will have something up and running over the next few weeks or so.

**Comment by nhobes** [comment]
Closing this now as you should be able to do this now with the inclusion of configurability and make css overrides in your app.css file.

https://petal.build/blog/Petal-Components-v1-0-released-Configurability-is-here
