### ISSUE TITLE
Avoid setting default text size

### ISSUE THREAD

**Issue by rupurt** [petalframework/petal_components#70]
## Problem

The library sets the default text size of many components to `text-sm` by default which breaks/restricts the base configuration of tailwind.

e.g. form inputs https://github.com/petalframework/petal_components/blob/main/lib/petal_components/form.ex#L473

## Solution

:scissors: `text-sm` from components and provide a property e.g. `prop :text_size, :string`

**Comment by mplatts** [comment]
If we remove text-sm then by default some of the components might look a little off - the goal of the library is to have nice-looking components work out of the box so developers don't have to worry too much about design.  So were you wanting to be able to change the base config of tailwind and see all your components change?

**Comment by rupurt** [comment]
@mplatts I feel like you always need to have escape hatches. If you want to apply a base text size you can set it in a custom theme.

**Comment by nhobes** [comment]
Closing as you should be able to modify this with configurability.

https://petal.build/blog/Petal-Components-v1-0-released-Configurability-is-here
