### ISSUE TITLE
Dialog components

### ISSUE THREAD

**Issue by saleyn** [petalframework/petal_components#74]
I implemented [this small javascript library](https://github.com/saleyn/js-dialog) as a replacement of browsers standard alert/confirm/prompt components, and thought that it would be a good idea in integrate it with petal components.  For that they'd likely need to share styling options.  Let me know if there's interest in adding this functionality to petal.

**Comment by mplatts** [comment]
Hi @saleyn, nice work on the alert components. The standard ones are definitely lacking. 

For it to work in Petal:

1. component written in HEEX
1. styled with Tailwind CSS
2. JS would need to be inlined somehow as we want these components to work out of the box
3. can work in both Live and Dead views in Phoenix
