### ISSUE TITLE
Migrating to LiveView 0.18

### ISSUE THREAD

**Issue by anzaika** [petalframework/petal_components#75]
LiveView is about to introduce a `link` helper when 0.18 releases (excerpt from LiveView Changelog)

> v0.18 includes a number of new function components which replace their EEx expression counterparts <%= ... %>. For example, live_redirect, live_patch, and Phoenix.HTML's link have been replaced by a unified Phoenix.Component.link/1 function component:
```
<.link href="https://myapp.com">my app</.link>
<.link navigate={@path}>remount</.link>
<.link patch={@path}>patch</.link>
```

This conflicts with Petal's own `link` helper and leads to these errors:

```
== Compilation error in file lib/petal_boilerplate_web/live/page_live.ex ==
** (CompileError) lib/petal_boilerplate_web/live/page_live.ex:143: function link/1 imported from both PetalComponents.Link and Phoenix.LiveView.Helpers, call is ambiguous
```

I can prepare a PR to fix this. We just need to discuss the solution. Am I correct that renaming a `link` helper in Petal is the best solution, and we just need to figure out the new name or is there a better one?

**Comment by anzaika** [comment]
Found there's already a pull request for this https://github.com/petalframework/petal_components/pull/46

Sorry for all the fuss.

**Comment by mplatts** [comment]
All good. I'm thinking of cancelling that PR and going with a renaming option. As it will be easier to migrate a name change vs changing the props around

**Comment by mplatts** [comment]
thinking `<.a>`

**Comment by anzaika** [comment]
Thanks for coming back. I appreciate it!

`<.a>` makes perfect sense. I'll prepare a PR then.

**Comment by mplatts** [comment]
We have migrated to 0.18 see https://github.com/petalframework/petal_components/blob/main/UPGRADE_GUIDE.md
