### ISSUE TITLE
Component wrappers for the Surface library

### ISSUE THREAD

**Issue by saleyn** [petalframework/petal_components#76]
Would you consider a feature of creating a layer of wrappers to be able to use Petal's component styles with the Surface library?

Otherwise Petal components don't seem to be friendly to Surface:
```elixir
# Surface:

<Form for={:user}>
  <Field name={:email}>
    <Label>E-mail</Label>
    <TextInput value={@user["email"]}/>
  </Field>
</Form>

# Petal:

<.form let={f} for={:user}>
  <.form_label form={f} field={:email}/>
  <.text_input form={f} field={:email}/>
  <.form_field_error form={f} field={:email}/>
</.form>
```

Or is there some other suggested way of doing this that I am missing?

**Comment by mplatts** [comment]
I'm not really following along with the Surface project - I don't think surface allows mixing in Phoenix.Components as of yet.
