### ISSUE TITLE
Use Heroicons Elixir library

### ISSUE THREAD

**Issue by mplatts** [petalframework/petal_components#77]
[Heroicons](https://heroicons.com/) recently upgraded to 2.0.

We could either upgrade our own icon component builder, or just import this separate Hex lib: https://github.com/mveytsman/heroicons_elixir

**Comment by chvanikoff** [comment]
My vote is for the lib. Let your lib focus on the components, not the icons. It should be trivial to migrate.

**Comment by mplatts** [comment]
We have renamed `Heroicons` to `HeroiconsV1`. To use Heroicons V2, please use https://github.com/mveytsman/heroicons_elixir
