### ISSUE TITLE
Multiselect

### ISSUE THREAD

**Issue by chvanikoff** [petalframework/petal_components#80]
Hi, what are your thoughts on implementing multiselect component besides the checkbox group?
Here is an [excellent design spec on multiselects](https://design.procore.com/multi-select) and the related [demo/implementation in React](https://core.procore.com/next/web/components/multi-select/react/), in case anyone is interested.

**Comment by mplatts** [comment]
It would be cool - I think it'd need a lot of Javascript to make it snappy.  Liveview might be a bit too laggy for what you'd expect to be lightning fast. Usually, I'd use a hook that loads an external library like [Slim select](https://slimselectjs.com/).
