### ISSUE TITLE
Icons are missing chevron_up_down

### ISSUE THREAD

**Issue by ynnadrules** [petalframework/petal_components#82]
I noticed the `chevron-up-down` icon is missing from the set. I believe it's because it was accidentally missing from the available svg's in the heroicons repo's `optimized` folder. 

I noticed the [`optimized`](https://github.com/tailwindlabs/heroicons/tree/master/optimized) folder has change structure and so I think the heroicons mix task will need to be updated to handle the change.

**Comment by mplatts** [comment]
Hi @ynnadrules thanks yeah Heroicons recently updated to v2 while we are still on v1. 
There is a plan to remove our mix task and rely on another Heroicons hex library that has updated to v2 (https://github.com/petalframework/petal_components/issues/77).
