### ISSUE TITLE
Explicit color customization not working

### ISSUE THREAD

**Issue by aherranz** [petalframework/petal_components#93]
I tried to customize my color theme with explicit colors for primary and secondary in `tailwind.config.js`:

```
  theme: {
    extend: {
      colors: {
        primary: "#034EA2",
        secondary: "#563600",
      }
    },
  },
```

Then, the color primary is ignored in this component:

```
<.button color="primary" label="Primary" />
```

Nevertheless, if I define primary with an alias like

```
        primary: colors.violet,
```

It works perfectly.

I am not sure if this is a bug in the button component or if I am doing something wrong or if I am missing a prevous step to make it working.

Regards.

Version 0.18.3.

**Comment by mplatts** [comment]
Hey yeah the value should be an object like this:

```js

 theme: {
  extend: {
    colors: {
      primary: {
        50: "#fff7fd",
        100: "#fbe0f7",
        200: "#f9bdf1",
        300: "#ec94ed",
        400: "#cc6edc",
        500: "#a753c3",
        600: "#8640a7",
        700: "#66308d",
        800: "#492273",
        900: "#301057",
      };
    }
  },
},
```

Anything in `colors` like `colors.violet` is made by the Tailwind team. But you can make your own on sites like this one: https://uicolors.app/create
