### ISSUE TITLE
Z-index of disabled buttons off?

### ISSUE THREAD

**Issue by larshei** [petalframework/petal_components#94]
Just saw this on the component demo page:

![Screenshot_20221010-100359_Chrome.jpg](https://user-images.githubusercontent.com/22884787/194814241-4f77416e-bf09-4c4c-9027-aecc13358da7.jpg)

The buttons should probably be behind the top bar/menu.

**Comment by nhobes** [comment]
Thanks for letting me know, looking into it!

**Comment by nhobes** [comment]
Fixed in boilerplate update coming
