### ISSUE TITLE
Add tags to the card content

### ISSUE THREAD

**Issue by obsidienne** [petalframework/petal_components#95]
Hi,

I think the <.card_content> component should allow a tags attributes. Something like this

```
<.card_content category="My category" heading="Awesome heading" tags={[tag1, tag2, ..., tagn]}>
</.card_content>
```

The tag being a <.badge color="primary" variant="outline">

Is it a pull request interesting for you ?

**Comment by nhobes** [comment]
Sounds good! Do you have an example of the use cases/what it would look like?

**Comment by obsidienne** [comment]
Hi,

Something like that :)

<img width="429" alt="image" src="https://user-images.githubusercontent.com/1252097/195794151-6311b2a9-aa3a-4d3a-a19c-0745c8f932fa.png">

**Comment by nhobes** [comment]
That does look great and I can see the use case. Feel free to submit a PR if you get around to it and I'll take a look :)

**Comment by nhobes** [comment]
Closing for now.
